name: valgrind

on:
  push
jobs:
  memory_leak_test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Installing Valgrind
          run: sudo apt-get install valgrind
        - name: build
          run: make build
        - name: Checking memory leak
          run: make valgrind
